### ISSUE TITLE
Does it work with BitBucket cloud?

### ISSUE THREAD

**Issue by fjaeger** [cvitter/mattermost-bitbucket-bridge#8]
... or does it only work with BitBucket server?

**Comment by cvitter** [comment]
@fjaeger I don't have Cloud to test it against, only server. Please let me know if it does/doesn't work. If it doesn't maybe we can update the code to support Cloud as well.

**Comment by fjaeger** [comment]
@cvitter I was just wondering how to configure `bitbucket.server_url` in the configuration file in case of a cloud version of BitBucket

**Comment by cvitter** [comment]
@fjaeger Unfortunately I haven't used cloud - this is the base URL needed so that hyperlinks in the messages sent to Mattermost will link correctly back to the Bitbucket event on Bitbucket like:

[http://url/]users/craig (the url portion in square brackets is what needs to be in `bitbucket.server_url`. 
or
[http://url/]projects/PRJX/repos/mattermost-jenkins-slash/commits/0b9f70df648dc09811d23068faa1b42bc8cbb541

The rest of the URL is created by the application based on the content of the Bitbucket webhook.

**Comment by fjaeger** [comment]
Alright, I will give it a try soon and provide feedback! Thanks!

**Comment by cvitter** [comment]
Thank you!

**Comment by cvitter** [comment]
@fjaeger looks like you have added Cloud support in your fork of the project (https://github.com/Mailbutler/mattermost-bitbucket-bridge). Would you be interested in submitting a PR back?

**Comment by fjaeger** [comment]
Yes, I will create a PR when I am back from my vacation in December :-)
